### ISSUE TITLE
Panic when writing 1 byte to an empty `CrcStore`

### ISSUE THREAD

**Issue by xpe** [xpe/crc-store#1]
```
*********************************
CRASH_MIN: minimizing crash input: '/stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cccb25f14120310732a588beaa8cd7ce3524d32c' (12 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/stuff/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cccb25f14120310732a588beaa8cd7ce3524d32c 2>&1
CRASH_MIN: '/stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cccb25f14120310732a588beaa8cd7ce3524d32c' (12 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/stuff/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cccb25f14120310732a588beaa8cd7ce3524d32c -minimize_crash_internal_step=1 -exact_artifact_path=/stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1232496603
INFO: Loaded 1 modules   (9658 inline 8-bit counters): 9658 [0x100c90980, 0x100c92f3a), 
INFO: Loaded 1 PC tables (9658 PCs): 9658 [0x100c92f40,0x100cb8ae0), 
INFO: Starting MinimizeCrashInputInternalStep: 12
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 12 bytes
thread '<unnamed>' panicked at /stuff/crc-store/src/crc_store/write.rs:85:9:
assertion failed: self.inner_pos >= s
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==88561== ERROR: libFuzzer: deadly signal
    #0 0x000101683d44 in __sanitizer_print_stack_trace+0x28 (librustc-nightly_rt.asan.dylib:arm64+0x5bd44)
    #1 0x000100b21b6c in fuzzer::PrintStackTrace()+0x30 (fuzz_methods:arm64+0x10004db6c)
    #2 0x000100b14b00 in fuzzer::Fuzzer::CrashCallback()+0x54 (fuzz_methods:arm64+0x100040b00)
    #3 0x00019142a580 in _sigtramp+0x34 (libsystem_platform.dylib:arm64+0x4580)
    #4 0x90320001913f9c1c  (<unknown module>)
    #5 0x442e800191306a2c  (<unknown module>)
    #6 0xbc40000100bc79e0  (<unknown module>)
    #7 0x000100c117ac in std::process::abort::he51581417d9008c6+0x8 (fuzz_methods:arm64+0x10013d7ac)
    #8 0x000100b13a84 in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h6371a7f56ee867f5+0xb8 (fuzz_methods:arm64+0x10003fa84)
    #9 0x000100bbf3ec in std::panicking::rust_panic_with_hook::hd3f7e991067477e4+0x2a0 (fuzz_methods:arm64+0x1000eb3ec)
    #10 0x000100bbf03c in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::hff91e2bf957fd9d4+0x64 (fuzz_methods:arm64+0x1000eb03c)
    #11 0x000100bbcd44 in std::sys::backtrace::__rust_end_short_backtrace::he4610719ded42d6d+0x8 (fuzz_methods:arm64+0x1000e8d44)
    #12 0x000100bbed1c in rust_begin_unwind+0x1c (fuzz_methods:arm64+0x1000ead1c)
    #13 0x000100c136d4 in core::panicking::panic_fmt::ha0aacd903a199de9+0x1c (fuzz_methods:arm64+0x10013f6d4)
    #14 0x000100c13744 in core::panicking::panic::he2d769b73be5f366+0x30 (fuzz_methods:arm64+0x10013f744)
    #15 0x000100aee7bc in crc_store::crc_store::write::_$LT$impl$u20$crc_store..crc_store..store..CrcStore$LT$I$GT$$GT$::calc_prev_checksum::h45dbdd171e920eb7 write.rs:85
    #16 0x000100aef96c in crc_store::crc_store::write::_$LT$impl$u20$std..io..Write$u20$for$u20$crc_store..crc_store..store..CrcStore$LT$I$GT$$GT$::write::h0535d68724218a87 write.rs:27
    #17 0x000100af0ae4 in fuzz_methods::call_method::h0608bf8cd92dd5e2 fuzz_methods.rs:39
    #18 0x000100af03c4 in fuzz_methods::execute_seq::h4e41eabd04d0d985 fuzz_methods.rs:20
    #19 0x000100af1ffc in fuzz_methods::_::__libfuzzer_sys_run::h13de295751f5d141 fuzz_methods.rs:12
    #20 0x000100af19f8 in rust_fuzzer_test_input lib.rs:297
    #21 0x000100b0c5c4 in std::panicking::try::do_call::ha5973346fdfaef54+0xc4 (fuzz_methods:arm64+0x1000385c4)
    #22 0x000100b13cec in __rust_try+0x18 (fuzz_methods:arm64+0x10003fcec)
    #23 0x000100b131d4 in LLVMFuzzerTestOneInput+0x16c (fuzz_methods:arm64+0x10003f1d4)
    #24 0x000100b163c4 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x150 (fuzz_methods:arm64+0x1000423c4)
    #25 0x000100b18490 in fuzzer::Fuzzer::MinimizeCrashLoop(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&)+0x128 (fuzz_methods:arm64+0x100044490)
    #26 0x000100b35eac in fuzzer::MinimizeCrashInputInternalStep(fuzzer::Fuzzer*, fuzzer::InputCorpus*)+0x124 (fuzz_methods:arm64+0x100061eac)
    #27 0x000100b392e4 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1c08 (fuzz_methods:arm64+0x1000652e4)
    #28 0x000100b46cc8 in main+0x24 (fuzz_methods:arm64+0x100072cc8)
    #29 0x00019106f150  (<unknown module>)
    #30 0x6d667ffffffffffc  (<unknown module>)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 2 EraseBytes-EraseBytes-; base unit: 0000000000000000000000000000000000000000
0x3,0x67,0x0,0x0,0x0,0x47,0xe4,0xfc,0x27,0x7e,0xff,
\003g\000\000\000G\344\374'~\377
artifact_prefix='/stuff/crc-store/fuzz/artifacts/fuzz_methods/'; Test unit written to /stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2
Base64: A2cAAABH5Pwnfv8=
*********************************
CRASH_MIN: minimizing crash input: '/stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2' (11 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/stuff/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2 2>&1
CRASH_MIN: '/stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2' (11 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/stuff/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2 -minimize_crash_internal_step=1 -exact_artifact_path=/stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-a2de3e6ac9d80406a67f98c0115901c085a94524 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1233096716
INFO: Loaded 1 modules   (9658 inline 8-bit counters): 9658 [0x10020c980, 0x10020ef3a), 
INFO: Loaded 1 PC tables (9658 PCs): 9658 [0x10020ef40,0x100234ae0), 
INFO: Starting MinimizeCrashInputInternalStep: 11
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 11 bytes
INFO: Done MinimizeCrashInputInternalStep, no crashes found
CRASH_MIN: failed to minimize beyond /stuff/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2 (11 bytes), exiting

────────────────────────────────────────────────────────────────────────────────

Minimized artifact:

	fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2

Output of `std::fmt::Debug`:

	Sequence {
	    seg_len: 26371,
	    initial_bytes: [],
	    methods: [
	        Write {
	            buf: [
	                0,
	            ],
	        },
	    ],
	}

Reproduce with:

	cargo fuzz run fuzz_methods fuzz/artifacts/fuzz_methods/minimized-from-a898425ef14d2913ce8b871d2b2699130715a9d2
```

**Comment by xpe** [comment]
Focusing on the key parts:

```
thread '<unnamed>' panicked at /stuff/crc-store/src/crc_store/write.rs:85:9:
assertion failed: self.inner_pos >= s
[...]
==88561== ERROR: libFuzzer: deadly signal
[...]
    #15 0x000100aee7bc in crc_store::crc_store::write::_$LT$impl$u20$crc_store..crc_store..store..CrcStore$LT$I$GT$$GT$::calc_prev_checksum::h45dbdd171e920eb7 write.rs:85
    #16 0x000100aef96c in crc_store::crc_store::write::_$LT$impl$u20$std..io..Write$u20$for$u20$crc_store..crc_store..store..CrcStore$LT$I$GT$$GT$::write::h0535d68724218a87 write.rs:27
```

**Comment by xpe** [comment]
Suspected core problem: the design of `calc_and_write_prev_checksum()` (and its sub-functions) have a precondition that is too strict.

**Comment by xpe** [comment]
Note: the commit above renamed `calc_and_write_prev_checksum()` to `update_prev_checksum()`.
