### ISSUE TITLE
Assertion `left == right` failed: `validate.rs:57:9`

### ISSUE THREAD

**Issue by xpe** [xpe/crc-store#14]
```console
*********************************
CRASH_MIN: minimizing crash input: '/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-0f2d77678e3a93c642c5cd0fc2a543d4a08af2cd' (26 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_rwsv -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-0f2d77678e3a93c642c5cd0fc2a543d4a08af2cd 2>&1
CRASH_MIN: '/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-0f2d77678e3a93c642c5cd0fc2a543d4a08af2cd' (26 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_rwsv -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-0f2d77678e3a93c642c5cd0fc2a543d4a08af2cd -minimize_crash_internal_step=1 -exact_artifact_path=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-59c09505c2e9b3cc97597eae38445a98f058eb90 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2242208821
INFO: Loaded 1 modules   (9500 inline 8-bit counters): 9500 [0x102dfcd30, 0x102dff24c), 
INFO: Loaded 1 PC tables (9500 PCs): 9500 [0x102dff250,0x102e24410), 
INFO: Starting MinimizeCrashInputInternalStep: 26
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 26 bytes
thread '<unnamed>' panicked at /paths/crc-store/src/validate.rs:57:9:
assertion `left == right` failed
  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==56671== ERROR: libFuzzer: deadly signal
    #0 0x0001037efd44 in __sanitizer_print_stack_trace+0x28 (librustc-nightly_rt.asan.dylib:arm64+0x5bd44)
    #1 0x000102c8e2c8 in fuzzer::PrintStackTrace()+0x30 (fuzz_rwsv:arm64+0x10004a2c8)
    #2 0x000102c8157c in fuzzer::Fuzzer::CrashCallback()+0x54 (fuzz_rwsv:arm64+0x10003d57c)
    #3 0x000198146580 in _sigtramp+0x34 (libsystem_platform.dylib:arm64+0x4580)
    #4 0x7a2a000198115c1c  (<unknown module>)
    #5 0xbe6c000198022a2c  (<unknown module>)
    #6 0xd16d800102d3473c  (<unknown module>)
    #7 0x000102d7e724 in std::process::abort::h4307c511456be812+0x8 (fuzz_rwsv:arm64+0x10013a724)
    #8 0x000102c804f0 in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h1ed27d9e431f57ab+0xb8 (fuzz_rwsv:arm64+0x10003c4f0)
    #9 0x000102d2c114 in std::panicking::rust_panic_with_hook::he9e7a691abc6490c+0x2a0 (fuzz_rwsv:arm64+0x1000e8114)
    #10 0x000102d2bd8c in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h76e8e9b8127ee308+0x8c (fuzz_rwsv:arm64+0x1000e7d8c)
    #11 0x000102d29b30 in std::sys::backtrace::__rust_end_short_backtrace::h96d8ed392cde8e6b+0x8 (fuzz_rwsv:arm64+0x1000e5b30)
    #12 0x000102d2ba44 in rust_begin_unwind+0x1c (fuzz_rwsv:arm64+0x1000e7a44)
    #13 0x000102d80450 in core::panicking::panic_fmt::hf952f5ecf9ded51a+0x1c (fuzz_rwsv:arm64+0x10013c450)
    #14 0x000102d807e4 in core::panicking::assert_failed_inner::hd94f6f2b420dd5d9+0x104 (fuzz_rwsv:arm64+0x10013c7e4)
    #15 0x000102d7c6dc in core::panicking::assert_failed::ha85c08a952b0606a panicking.rs:367
    #16 0x000102c6ec70 in crc_store::validate::_$LT$impl$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::validate_next_segments::hbff056027e413e1c validate.rs:57
    #17 0x000102c6fcc0 in crc_store::validate::_$LT$impl$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::validate_smaller_segments::hf6bb5cb5037d3ac2 validate.rs:25
    #18 0x000102c716cc in fuzz_rwsv::call_method::hd2012d002949532f fuzz_rwsv.rs:99
    #19 0x000102c70e4c in fuzz_rwsv::execute_setup::h81ee3071f082e191 fuzz_rwsv.rs:55
    #20 0x000102c78d50 in fuzz_rwsv::_::__libfuzzer_sys_run::he06fbde3cd780d3c fuzz_rwsv.rs:42
    #21 0x000102c78754 in rust_fuzzer_test_input lib.rs:297
    #22 0x000102c79030 in std::panicking::try::do_call::h12046b7db380eecf+0xc4 (fuzz_rwsv:arm64+0x100035030)
    #23 0x000102c80758 in __rust_try+0x18 (fuzz_rwsv:arm64+0x10003c758)
    #24 0x000102c7fc40 in LLVMFuzzerTestOneInput+0x16c (fuzz_rwsv:arm64+0x10003bc40)
    #25 0x000102c82e50 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x150 (fuzz_rwsv:arm64+0x10003ee50)
    #26 0x000102c84f5c in fuzzer::Fuzzer::MinimizeCrashLoop(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&)+0x128 (fuzz_rwsv:arm64+0x100040f5c)
    #27 0x000102ca21cc in fuzzer::MinimizeCrashInputInternalStep(fuzzer::Fuzzer*, fuzzer::InputCorpus*)+0xd8 (fuzz_rwsv:arm64+0x10005e1cc)
    #28 0x000102ca55e0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1c4c (fuzz_rwsv:arm64+0x1000615e0)
    #29 0x000102cb2d78 in main+0x24 (fuzz_rwsv:arm64+0x10006ed78)
    #30 0x000197d8b150  (<unknown module>)
    #31 0x57487ffffffffffc  (<unknown module>)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 EraseBytes-; base unit: 0000000000000000000000000000000000000000
0x0,0x1,0x0,0x0,0x0,0x0,0x1,0x0,0x20,0x80,0x3d,0x0,0x73,0x73,0x73,0x73,0x0,0x0,0x5d,0xaf,0x0,0x2b,0xff,0x2b,
\000\001\000\000\000\000\001\000 \200=\000ssss\000\000]\257\000+\377+
artifact_prefix='/paths/crc-store/fuzz/artifacts/fuzz_rwsv/'; Test unit written to /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-59c09505c2e9b3cc97597eae38445a98f058eb90
Base64: AAEAAAAAAQAggD0Ac3NzcwAAXa8AK/8r
*********************************
CRASH_MIN: minimizing crash input: '/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-59c09505c2e9b3cc97597eae38445a98f058eb90' (24 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_rwsv -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-59c09505c2e9b3cc97597eae38445a98f058eb90 2>&1
CRASH_MIN: '/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-59c09505c2e9b3cc97597eae38445a98f058eb90' (24 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_rwsv -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-59c09505c2e9b3cc97597eae38445a98f058eb90 -minimize_crash_internal_step=1 -exact_artifact_path=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2242820725
INFO: Loaded 1 modules   (9500 inline 8-bit counters): 9500 [0x10259cd30, 0x10259f24c), 
INFO: Loaded 1 PC tables (9500 PCs): 9500 [0x10259f250,0x1025c4410), 
INFO: Starting MinimizeCrashInputInternalStep: 24
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 24 bytes
thread '<unnamed>' panicked at /paths/crc-store/src/validate.rs:57:9:
assertion `left == right` failed
  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==56679== ERROR: libFuzzer: deadly signal
    #0 0x000102f8fd44 in __sanitizer_print_stack_trace+0x28 (librustc-nightly_rt.asan.dylib:arm64+0x5bd44)
    #1 0x00010242e2c8 in fuzzer::PrintStackTrace()+0x30 (fuzz_rwsv:arm64+0x10004a2c8)
    #2 0x00010242157c in fuzzer::Fuzzer::CrashCallback()+0x54 (fuzz_rwsv:arm64+0x10003d57c)
    #3 0x000198146580 in _sigtramp+0x34 (libsystem_platform.dylib:arm64+0x4580)
    #4 0x47b000198115c1c  (<unknown module>)
    #5 0x5b3d000198022a2c  (<unknown module>)
    #6 0x633d0001024d473c  (<unknown module>)
    #7 0x00010251e724 in std::process::abort::h4307c511456be812+0x8 (fuzz_rwsv:arm64+0x10013a724)
    #8 0x0001024204f0 in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h1ed27d9e431f57ab+0xb8 (fuzz_rwsv:arm64+0x10003c4f0)
    #9 0x0001024cc114 in std::panicking::rust_panic_with_hook::he9e7a691abc6490c+0x2a0 (fuzz_rwsv:arm64+0x1000e8114)
    #10 0x0001024cbd8c in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h76e8e9b8127ee308+0x8c (fuzz_rwsv:arm64+0x1000e7d8c)
    #11 0x0001024c9b30 in std::sys::backtrace::__rust_end_short_backtrace::h96d8ed392cde8e6b+0x8 (fuzz_rwsv:arm64+0x1000e5b30)
    #12 0x0001024cba44 in rust_begin_unwind+0x1c (fuzz_rwsv:arm64+0x1000e7a44)
    #13 0x000102520450 in core::panicking::panic_fmt::hf952f5ecf9ded51a+0x1c (fuzz_rwsv:arm64+0x10013c450)
    #14 0x0001025207e4 in core::panicking::assert_failed_inner::hd94f6f2b420dd5d9+0x104 (fuzz_rwsv:arm64+0x10013c7e4)
    #15 0x00010251c6dc in core::panicking::assert_failed::ha85c08a952b0606a panicking.rs:367
    #16 0x00010240ec70 in crc_store::validate::_$LT$impl$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::validate_next_segments::hbff056027e413e1c validate.rs:57
    #17 0x00010240fcc0 in crc_store::validate::_$LT$impl$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::validate_smaller_segments::hf6bb5cb5037d3ac2 validate.rs:25
    #18 0x0001024116cc in fuzz_rwsv::call_method::hd2012d002949532f fuzz_rwsv.rs:99
    #19 0x000102410e4c in fuzz_rwsv::execute_setup::h81ee3071f082e191 fuzz_rwsv.rs:55
    #20 0x000102418d50 in fuzz_rwsv::_::__libfuzzer_sys_run::he06fbde3cd780d3c fuzz_rwsv.rs:42
    #21 0x000102418754 in rust_fuzzer_test_input lib.rs:297
    #22 0x000102419030 in std::panicking::try::do_call::h12046b7db380eecf+0xc4 (fuzz_rwsv:arm64+0x100035030)
    #23 0x000102420758 in __rust_try+0x18 (fuzz_rwsv:arm64+0x10003c758)
    #24 0x00010241fc40 in LLVMFuzzerTestOneInput+0x16c (fuzz_rwsv:arm64+0x10003bc40)
    #25 0x000102422e50 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x150 (fuzz_rwsv:arm64+0x10003ee50)
    #26 0x000102424f5c in fuzzer::Fuzzer::MinimizeCrashLoop(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&)+0x128 (fuzz_rwsv:arm64+0x100040f5c)
    #27 0x0001024421cc in fuzzer::MinimizeCrashInputInternalStep(fuzzer::Fuzzer*, fuzzer::InputCorpus*)+0xd8 (fuzz_rwsv:arm64+0x10005e1cc)
    #28 0x0001024455e0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1c4c (fuzz_rwsv:arm64+0x1000615e0)
    #29 0x000102452d78 in main+0x24 (fuzz_rwsv:arm64+0x10006ed78)
    #30 0x000197d8b150  (<unknown module>)
    #31 0xf437ffffffffffc  (<unknown module>)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 EraseBytes-; base unit: 0000000000000000000000000000000000000000
0x0,0x1,0x0,0x0,0x0,0x0,0x1,0x0,0x20,0x80,0x3d,0x0,0x73,0x73,0x73,0x73,0x0,0x0,0x5d,0xaf,0x0,0x2b,0xff,
\000\001\000\000\000\000\001\000 \200=\000ssss\000\000]\257\000+\377
artifact_prefix='/paths/crc-store/fuzz/artifacts/fuzz_rwsv/'; Test unit written to /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb
Base64: AAEAAAAAAQAggD0Ac3NzcwAAXa8AK/8=
*********************************
CRASH_MIN: minimizing crash input: '/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb' (23 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_rwsv -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb 2>&1
CRASH_MIN: '/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb' (23 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_rwsv -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb -minimize_crash_internal_step=1 -exact_artifact_path=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-ce57794c28269d53fc0122b2f29c52df00c1f9f9 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2243433068
INFO: Loaded 1 modules   (9500 inline 8-bit counters): 9500 [0x1005c8d30, 0x1005cb24c), 
INFO: Loaded 1 PC tables (9500 PCs): 9500 [0x1005cb250,0x1005f0410), 
INFO: Starting MinimizeCrashInputInternalStep: 23
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 23 bytes
INFO: Done MinimizeCrashInputInternalStep, no crashes found
CRASH_MIN: failed to minimize beyond /paths/crc-store/fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb (23 bytes), exiting

────────────────────────────────────────────────────────────────────────────────

Minimized artifact:

	fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb

Output of `std::fmt::Debug`:

	Setup {
	    seg_len: 256,
	    buf_len: 65536,
	    validate_on_read: false,
	    initial_bytes: [],
	    methods: [
	        Write {
	            buf: [
	                0,
	            ],
	        },
	        Validate,
	    ],
	}

Reproduce with:

	cargo fuzz run fuzz_rwsv fuzz/artifacts/fuzz_rwsv/minimized-from-b276eee9578795300aa326bf8adae2d48b61dddb
```

**Comment by xpe** [comment]
The relevant part of the call stack is:

```
#16 ... validate_next_segments::h376a8bf7d0f9d380 validate.rs:59
#17 ... validate_smaller_segments::h595df3cdef51828d validate.rs:27
```

**Comment by xpe** [comment]
Note to self (and whatever technologies are scraping these comments, which I hope are doing so lawfully): my extensive use of `assert` in the code has been quite valuable in catching subtle bugs.
