### ISSUE TITLE
Assertion failed: offset <= b: `write.rs:60:9`

### ISSUE THREAD

**Issue by xpe** [xpe/crc-store#16]
```console
% cargo fuzz run fuzz_rwsv
    Finished `release` profile [optimized + debuginfo] target(s) in 0.00s
    Finished `release` profile [optimized + debuginfo] target(s) in 0.00s
     Running `fuzz/target/aarch64-apple-darwin/release/fuzz_rwsv -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_rwsv/ /paths/crc-store/fuzz/corpus/fuzz_rwsv`
fuzz_rwsv(65951,0x1fff64f40) malloc: nano zone abandoned due to inability to reserve vm space.
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1927089856
INFO: Loaded 1 modules   (9531 inline 8-bit counters): 9531 [0x104d94c20, 0x104d9715b), 
INFO: Loaded 1 PC tables (9531 PCs): 9531 [0x104d97160,0x104dbc510), 
INFO:      465 files found in /paths/crc-store/fuzz/corpus/fuzz_rwsv
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 465 min: 9b max: 677b total: 55343b rss: 52Mb
#466	INITED cov: 575 ft: 2590 corp: 294/35Kb exec/s: 0 rss: 73Mb
#567	REDUCE cov: 575 ft: 2590 corp: 294/35Kb lim: 677 exec/s: 0 rss: 75Mb L: 63/677 MS: 1 EraseBytes-
#964	NEW    cov: 575 ft: 2592 corp: 295/36Kb lim: 677 exec/s: 0 rss: 83Mb L: 665/677 MS: 2 ChangeByte-InsertRepeatedBytes-
#1142	REDUCE cov: 575 ft: 2592 corp: 295/36Kb lim: 677 exec/s: 0 rss: 86Mb L: 120/677 MS: 3 EraseBytes-ChangeBit-InsertByte-
#1218	REDUCE cov: 575 ft: 2592 corp: 295/36Kb lim: 677 exec/s: 0 rss: 87Mb L: 70/677 MS: 1 EraseBytes-
#1324	REDUCE cov: 575 ft: 2592 corp: 295/36Kb lim: 677 exec/s: 0 rss: 88Mb L: 133/677 MS: 1 EraseBytes-
thread '<unnamed>' panicked at /paths/crc-store/src/write.rs:60:9:
assertion failed: offset <= b
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==65951== ERROR: libFuzzer: deadly signal
    #0 0x000105787d44 in __sanitizer_print_stack_trace+0x28 (librustc-nightly_rt.asan.dylib:arm64+0x5bd44)
    #1 0x000104c26364 in fuzzer::PrintStackTrace()+0x30 (fuzz_rwsv:arm64+0x10004a364)
    #2 0x000104c19618 in fuzzer::Fuzzer::CrashCallback()+0x54 (fuzz_rwsv:arm64+0x10003d618)
    #3 0x000198146580 in _sigtramp+0x34 (libsystem_platform.dylib:arm64+0x4580)
    #4 0xcf61000198115c1c  (<unknown module>)
    #5 0xd268000198022a2c  (<unknown module>)
    #6 0x6266800104ccc724  (<unknown module>)
    #7 0x000104d167f0 in std::process::abort::h4307c511456be812+0x8 (fuzz_rwsv:arm64+0x10013a7f0)
    #8 0x000104c1858c in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h1ed27d9e431f57ab+0xb8 (fuzz_rwsv:arm64+0x10003c58c)
    #9 0x000104cc40fc in std::panicking::rust_panic_with_hook::he9e7a691abc6490c+0x2a0 (fuzz_rwsv:arm64+0x1000e80fc)
    #10 0x000104cc3d4c in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h76e8e9b8127ee308+0x64 (fuzz_rwsv:arm64+0x1000e7d4c)
    #11 0x000104cc1b18 in std::sys::backtrace::__rust_end_short_backtrace::h96d8ed392cde8e6b+0x8 (fuzz_rwsv:arm64+0x1000e5b18)
    #12 0x000104cc3a2c in rust_begin_unwind+0x1c (fuzz_rwsv:arm64+0x1000e7a2c)
    #13 0x000104d1851c in core::panicking::panic_fmt::hf952f5ecf9ded51a+0x1c (fuzz_rwsv:arm64+0x10013c51c)
    #14 0x000104d1858c in core::panicking::panic::ha634db1d0ed9b55a+0x30 (fuzz_rwsv:arm64+0x10013c58c)
    #15 0x000104c031a8 in crc_store::write::_$LT$impl$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::write_with_checksums::h78db783e1a5416a7 write.rs:60
    #16 0x000104c09684 in fuzz_rwsv::call_method::hd2012d002949532f fuzz_rwsv.rs:72
    #17 0x000104c08d68 in fuzz_rwsv::execute_setup::h81ee3071f082e191 fuzz_rwsv.rs:55
    #18 0x000104c10dd4 in fuzz_rwsv::_::__libfuzzer_sys_run::he06fbde3cd780d3c fuzz_rwsv.rs:42
    #19 0x000104c107d8 in rust_fuzzer_test_input lib.rs:297
    #20 0x000104c110cc in std::panicking::try::do_call::h12046b7db380eecf+0xc4 (fuzz_rwsv:arm64+0x1000350cc)
    #21 0x000104c187f4 in __rust_try+0x18 (fuzz_rwsv:arm64+0x10003c7f4)
    #22 0x000104c17cdc in LLVMFuzzerTestOneInput+0x16c (fuzz_rwsv:arm64+0x10003bcdc)
    #23 0x000104c1aeec in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x150 (fuzz_rwsv:arm64+0x10003eeec)
    #24 0x000104c1a580 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (fuzz_rwsv:arm64+0x10003e580)
    #25 0x000104c1bfe8 in fuzzer::Fuzzer::MutateAndTestOne()+0x234 (fuzz_rwsv:arm64+0x10003ffe8)
    #26 0x000104c1cde8 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x358 (fuzz_rwsv:arm64+0x100040de8)
    #27 0x000104c3d7d0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1da0 (fuzz_rwsv:arm64+0x1000617d0)
    #28 0x000104c4ae14 in main+0x24 (fuzz_rwsv:arm64+0x10006ee14)
    #29 0x000197d8b150  (<unknown module>)
    #30 0xc1017ffffffffffc  (<unknown module>)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 CopyPart-; base unit: fdb68efb6c3e7aaa6f2b58d06a7d7289ecd8b30f
artifact_prefix='/paths/crc-store/fuzz/artifacts/fuzz_rwsv/'; Test unit written to /paths/crc-store/fuzz/artifacts/fuzz_rwsv/crash-2b404e914fb8837701c03ad953aa01d6a0e82181

────────────────────────────────────────────────────────────────────────────────

Failing input:

	fuzz/artifacts/fuzz_rwsv/crash-2b404e914fb8837701c03ad953aa01d6a0e82181

Output of `std::fmt::Debug`:

	Setup {
	    seg_len: 256,
	    buf_len: 32768,
	    validate_on_read: false,
	    initial_bytes: [],
	    methods: [
	        Write {
	            buf: [
	                5,
	                5,
	                5,
	            ],
	        },
	        Write {
	            buf: [
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                5,
	                111,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                253,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                5,
	                111,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                253,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                239,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                239,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                239,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                239,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                41,
	                255,
	                255,
	                175,
	            ],
	        },
	        Validate,
	        Write {
	            buf: [
	                255,
	                255,
	                255,
	                255,
	                255,
	                5,
	                111,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                255,
	                0,
	            ],
	        },
	    ],
	}

Reproduce with:

	cargo fuzz run fuzz_rwsv fuzz/artifacts/fuzz_rwsv/crash-2b404e914fb8837701c03ad953aa01d6a0e82181

Minimize test case with:

	cargo fuzz tmin fuzz_rwsv fuzz/artifacts/fuzz_rwsv/crash-2b404e914fb8837701c03ad953aa01d6a0e82181

────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit status: 77
```

**Comment by xpe** [comment]
I want to highlight what the fix does (from the commit message above, but not shown here clearly):

> Return the inner I/O object seek position to its original position
> after the call to `validate()` is done.
