### ISSUE TITLE
Assertion failed: `self.inner_pos % s < b` in `read.rs:12:9`

### ISSUE THREAD

**Issue by xpe** [xpe/crc-store#4]
```console
*********************************
CRASH_MIN: minimizing crash input: '/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-526e1bf6ea949fb8d73355994e00a80c45225ec0' (22 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-526e1bf6ea949fb8d73355994e00a80c45225ec0 2>&1
CRASH_MIN: '/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-526e1bf6ea949fb8d73355994e00a80c45225ec0' (22 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-526e1bf6ea949fb8d73355994e00a80c45225ec0 -minimize_crash_internal_step=1 -exact_artifact_path=/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1936211343
INFO: Loaded 1 modules   (9887 inline 8-bit counters): 9887 [0x100cbd220, 0x100cbf8bf), 
INFO: Loaded 1 PC tables (9887 PCs): 9887 [0x100cbf8c0,0x100ce62b0), 
INFO: Starting MinimizeCrashInputInternalStep: 22
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 22 bytes
thread '<unnamed>' panicked at /paths/crc-store/src/read.rs:12:9:
assertion failed: self.inner_pos % s < b
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==12277== ERROR: libFuzzer: deadly signal
    #0 0x0001016b3d44 in __sanitizer_print_stack_trace+0x28 (librustc-nightly_rt.asan.dylib:arm64+0x5bd44)
    #1 0x000100b4cbc4 in fuzzer::PrintStackTrace()+0x30 (fuzz_methods:arm64+0x100050bc4)
    #2 0x000100b3fe78 in fuzzer::Fuzzer::CrashCallback()+0x54 (fuzz_methods:arm64+0x100043e78)
    #3 0x000198146580 in _sigtramp+0x34 (libsystem_platform.dylib:arm64+0x4580)
    #4 0x5a0a000198115c1c  (<unknown module>)
    #5 0x4f3c800198022a2c  (<unknown module>)
    #6 0x2676000100bf32d8  (<unknown module>)
    #7 0x000100c3cfc0 in std::process::abort::he51581417d9008c6+0x8 (fuzz_methods:arm64+0x100140fc0)
    #8 0x000100b3edec in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h4a101166ad03ec22+0xb8 (fuzz_methods:arm64+0x100042dec)
    #9 0x000100beace4 in std::panicking::rust_panic_with_hook::hd3f7e991067477e4+0x2a0 (fuzz_methods:arm64+0x1000eece4)
    #10 0x000100bea934 in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::hff91e2bf957fd9d4+0x64 (fuzz_methods:arm64+0x1000ee934)
    #11 0x000100be863c in std::sys::backtrace::__rust_end_short_backtrace::he4610719ded42d6d+0x8 (fuzz_methods:arm64+0x1000ec63c)
    #12 0x000100bea614 in rust_begin_unwind+0x1c (fuzz_methods:arm64+0x1000ee614)
    #13 0x000100c3eee8 in core::panicking::panic_fmt::ha0aacd903a199de9+0x1c (fuzz_methods:arm64+0x100142ee8)
    #14 0x000100c3ef58 in core::panicking::panic::he2d769b73be5f366+0x30 (fuzz_methods:arm64+0x100142f58)
    #15 0x000100b163f4 in crc_store::read::_$LT$impl$u20$std..io..Read$u20$for$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::read::hb18ce1942c3e2cb6 read.rs:12
    #16 0x000100b1bbc4 in fuzz_methods::call_method::h525bcc52ddcf1785 fuzz_methods.rs:41
    #17 0x000100b1b27c in fuzz_methods::execute_setup::h10418666016d2976 fuzz_methods.rs:25
    #18 0x000100b1cde4 in fuzz_methods::_::__libfuzzer_sys_run::h0a42db61cb2cf9f9 fuzz_methods.rs:12
    #19 0x000100b1c7ec in rust_fuzzer_test_input lib.rs:297
    #20 0x000100b3792c in std::panicking::try::do_call::h0c5fd4e812973d53+0xc4 (fuzz_methods:arm64+0x10003b92c)
    #21 0x000100b3f054 in __rust_try+0x18 (fuzz_methods:arm64+0x100043054)
    #22 0x000100b3e53c in LLVMFuzzerTestOneInput+0x16c (fuzz_methods:arm64+0x10004253c)
    #23 0x000100b4174c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x150 (fuzz_methods:arm64+0x10004574c)
    #24 0x000100b43858 in fuzzer::Fuzzer::MinimizeCrashLoop(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&)+0x128 (fuzz_methods:arm64+0x100047858)
    #25 0x000100b60ac8 in fuzzer::MinimizeCrashInputInternalStep(fuzzer::Fuzzer*, fuzzer::InputCorpus*)+0xd8 (fuzz_methods:arm64+0x100064ac8)
    #26 0x000100b63edc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1c4c (fuzz_methods:arm64+0x100067edc)
    #27 0x000100b71674 in main+0x24 (fuzz_methods:arm64+0x100075674)
    #28 0x000197d8b150  (<unknown module>)
    #29 0xc206fffffffffffc  (<unknown module>)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 EraseBytes-; base unit: 0000000000000000000000000000000000000000
0x8,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x83,0x83,0x83,0x83,0x0,0xb,0x95,
\010\000\000\000\000\010\000\000\000\000\001\000\000\203\203\203\203\000\013\225
artifact_prefix='/paths/crc-store/fuzz/artifacts/fuzz_methods/'; Test unit written to /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d
Base64: CAAAAAAIAAAAAAEAAIODg4MAC5U=
*********************************
CRASH_MIN: minimizing crash input: '/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d' (20 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d 2>&1
CRASH_MIN: '/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d' (20 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d -minimize_crash_internal_step=1 -exact_artifact_path=/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-c16101b06cfc832134fcc2912f687003bfa17f66 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1936796366
INFO: Loaded 1 modules   (9887 inline 8-bit counters): 9887 [0x103105220, 0x1031078bf), 
INFO: Loaded 1 PC tables (9887 PCs): 9887 [0x1031078c0,0x10312e2b0), 
INFO: Starting MinimizeCrashInputInternalStep: 20
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 20 bytes
INFO: Done MinimizeCrashInputInternalStep, no crashes found
CRASH_MIN: failed to minimize beyond /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d (20 bytes), exiting

────────────────────────────────────────────────────────────────────────────────

Minimized artifact:

	fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d

Output of `std::fmt::Debug`:

	Setup {
	    seg_len: 8,
	    buf_len: 2048,
	    validate_on_read: false,
	    initial_bytes: [],
	    methods: [
	        Write {
	            buf: [
	                131,
	            ],
	        },
	        Read {
	            buf_len: 0,
	        },
	    ],
	}

Reproduce with:

	cargo fuzz run fuzz_methods fuzz/artifacts/fuzz_methods/minimized-from-b476f3cf8d269cca10a9b6f921eaa15e95e8626d
```

**Comment by xpe** [comment]
```console
thread '<unnamed>' panicked at /paths/crc-store/src/read.rs:12:9:
assertion failed: self.inner_pos % s < b
```

The `Setup` causes `read()` to begin by reading at the end of a just-written file*.

Since the segment length (`seg_len`) is 8, the `inner_len` 

\* When I say "file", technically I mean a file-like I/O object.

**Comment by xpe** [comment]
This raises a question: After writing, where should the function leave the `inner_pos`?

This is what I currently have documented for `CrcStore`:

```rust
/// ## Invariants
///
/// For all functions, the following invariants must be true by the time a
/// function returns.
/// - `inner_pos` will:
///    - match the `inner` position
///    - always point to a body byte position
/// - `inner_len` will match the `inner` length
```

Making this happen for a {not-full-length final segment}* is a little tricky.

One way to do this is to "rewind" the `inner_pos` by 4 bytes in the case of writing a {not-full-length final segment}.

\* I put the phrase in curly braces because it is a mouthful, and I find it easier to parse this way.
