### ISSUE TITLE
Attempt to add with overflow: `seek.rs:174:14`

### ISSUE THREAD

**Issue by xpe** [xpe/crc-store#5]
```console
% cargo fuzz run fuzz_methods
    Finished `release` profile [optimized + debuginfo] target(s) in 0.01s
    Finished `release` profile [optimized + debuginfo] target(s) in 0.00s
     Running `fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ /paths/crc-store/fuzz/corpus/fuzz_methods`
fuzz_methods(17489,0x1fff64f40) malloc: nano zone abandoned due to inability to reserve vm space.
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3003304890
INFO: Loaded 1 modules   (9891 inline 8-bit counters): 9891 [0x104255220, 0x1042578c3), 
INFO: Loaded 1 PC tables (9891 PCs): 9891 [0x1042578c8,0x10427e2f8), 
INFO:       75 files found in /paths/crc-store/fuzz/corpus/fuzz_methods
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 75 min: 9b max: 33b total: 1558b rss: 51Mb
#76	INITED cov: 359 ft: 564 corp: 63/1326b exec/s: 0 rss: 55Mb
#272	NEW    cov: 359 ft: 574 corp: 64/1359b lim: 33 exec/s: 0 rss: 56Mb L: 33/33 MS: 1 CopyPart-
thread '<unnamed>' panicked at /paths/crc-store/src/seek.rs:174:14:
attempt to add with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==17489== ERROR: libFuzzer: deadly signal
    #0 0x000104c4bd44 in __sanitizer_print_stack_trace+0x28 (librustc-nightly_rt.asan.dylib:arm64+0x5bd44)
    #1 0x0001040e4bc4 in fuzzer::PrintStackTrace()+0x30 (fuzz_methods:arm64+0x100050bc4)
    #2 0x0001040d7e78 in fuzzer::Fuzzer::CrashCallback()+0x54 (fuzz_methods:arm64+0x100043e78)
    #3 0x000198146580 in _sigtramp+0x34 (libsystem_platform.dylib:arm64+0x4580)
    #4 0xc711000198115c1c  (<unknown module>)
    #5 0x4476800198022a2c  (<unknown module>)
    #6 0x4a0300010418b2d8  (<unknown module>)
    #7 0x0001041d4fc0 in std::process::abort::he51581417d9008c6+0x8 (fuzz_methods:arm64+0x100140fc0)
    #8 0x0001040d6dec in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h4a101166ad03ec22+0xb8 (fuzz_methods:arm64+0x100042dec)
    #9 0x000104182ce4 in std::panicking::rust_panic_with_hook::hd3f7e991067477e4+0x2a0 (fuzz_methods:arm64+0x1000eece4)
    #10 0x000104182934 in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::hff91e2bf957fd9d4+0x64 (fuzz_methods:arm64+0x1000ee934)
    #11 0x00010418063c in std::sys::backtrace::__rust_end_short_backtrace::he4610719ded42d6d+0x8 (fuzz_methods:arm64+0x1000ec63c)
    #12 0x000104182614 in rust_begin_unwind+0x1c (fuzz_methods:arm64+0x1000ee614)
    #13 0x0001041d6ee8 in core::panicking::panic_fmt::ha0aacd903a199de9+0x1c (fuzz_methods:arm64+0x100142ee8)
    #14 0x0001041d753c in core::panicking::panic_const::panic_const_add_overflow::h16ff257a83cf85e5+0x30 (fuzz_methods:arm64+0x10014353c)
    #15 0x0001040aecac in crc_store::seek::_$LT$impl$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::end_pos::h8de2fd7af20eaa1a seek.rs
    #16 0x0001040aef58 in crc_store::seek::_$LT$impl$u20$std..io..Seek$u20$for$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::seek::h8f4a4509bb1b4a1e seek.rs:25
    #17 0x0001040b3930 in fuzz_methods::call_method::h525bcc52ddcf1785 fuzz_methods.rs:52
    #18 0x0001040b327c in fuzz_methods::execute_setup::h10418666016d2976 fuzz_methods.rs:25
    #19 0x0001040b4de4 in fuzz_methods::_::__libfuzzer_sys_run::h0a42db61cb2cf9f9 fuzz_methods.rs:12
    #20 0x0001040b47ec in rust_fuzzer_test_input lib.rs:297
    #21 0x0001040cf92c in std::panicking::try::do_call::h0c5fd4e812973d53+0xc4 (fuzz_methods:arm64+0x10003b92c)
    #22 0x0001040d7054 in __rust_try+0x18 (fuzz_methods:arm64+0x100043054)
    #23 0x0001040d653c in LLVMFuzzerTestOneInput+0x16c (fuzz_methods:arm64+0x10004253c)
    #24 0x0001040d974c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x150 (fuzz_methods:arm64+0x10004574c)
    #25 0x0001040d8de0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)+0x48 (fuzz_methods:arm64+0x100044de0)
    #26 0x0001040da848 in fuzzer::Fuzzer::MutateAndTestOne()+0x234 (fuzz_methods:arm64+0x100046848)
    #27 0x0001040db648 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, std::__1::allocator<fuzzer::SizedFile>>&)+0x358 (fuzz_methods:arm64+0x100047648)
    #28 0x0001040fc030 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1da0 (fuzz_methods:arm64+0x100068030)
    #29 0x000104109674 in main+0x24 (fuzz_methods:arm64+0x100075674)
    #30 0x000197d8b150  (<unknown module>)
    #31 0x59317ffffffffffc  (<unknown module>)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 2 ChangeByte-CrossOver-; base unit: 8ae3e94fa2c7bbcd6d19cd79e76384f08ff2b230
0x8,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0xc3,0x1,0x0,0x0,0xc3,0xdb,0x0,0x0,0x8b,0x8b,0x26,0x8b,0x8b,0x0,0x1,0x0,0x7a,0x3b,0x0,0xb,0x95,
\010\000\000\000\000\010\000\000\000\000\303\001\000\000\303\333\000\000\213\213&\213\213\000\001\000z;\000\013\225
artifact_prefix='/paths/crc-store/fuzz/artifacts/fuzz_methods/'; Test unit written to /paths/crc-store/fuzz/artifacts/fuzz_methods/crash-c39e918f4c1ba7c85c755d5eef4d2117ed3cb668
Base64: CAAAAAAIAAAAAMMBAADD2wAAi4smi4sAAQB6OwALlQ==

────────────────────────────────────────────────────────────────────────────────

Failing input:

	fuzz/artifacts/fuzz_methods/crash-c39e918f4c1ba7c85c755d5eef4d2117ed3cb668

Output of `std::fmt::Debug`:

	Setup {
	    seg_len: 8,
	    buf_len: 2048,
	    validate_on_read: false,
	    initial_bytes: [],
	    methods: [
	        Seek {
	            seek_from: End(
	                8791027574479988363,
	            ),
	        },
	        Read {
	            buf_len: 0,
	        },
	    ],
	}

Reproduce with:

	cargo fuzz run fuzz_methods fuzz/artifacts/fuzz_methods/crash-c39e918f4c1ba7c85c755d5eef4d2117ed3cb668

Minimize test case with:

	cargo fuzz tmin fuzz_methods fuzz/artifacts/fuzz_methods/crash-c39e918f4c1ba7c85c755d5eef4d2117ed3cb668

────────────────────────────────────────────────────────────────────────────────

Error: Fuzz target exited with exit status: 77
```

**Comment by xpe** [comment]
Key details:

* empty initial `CrcStore`
* large seek from end
* the subsequent `read` is probably not necessary to surface this bug

```text
thread '<unnamed>' panicked at /paths/crc-store/src/seek.rs:174:14:
attempt to add with overflow
```
