### ISSUE TITLE
Capacity overflow: `write.rs:68`

### ISSUE THREAD

**Issue by xpe** [xpe/crc-store#9]
```console
*********************************
CRASH_MIN: minimizing crash input: '/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-5a258a7ca825decd8de91dfc46607e8e267f2ca0' (58 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-5a258a7ca825decd8de91dfc46607e8e267f2ca0 2>&1
CRASH_MIN: '/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-5a258a7ca825decd8de91dfc46607e8e267f2ca0' (58 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-5a258a7ca825decd8de91dfc46607e8e267f2ca0 -minimize_crash_internal_step=1 -exact_artifact_path=/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 543850795
INFO: Loaded 1 modules   (9890 inline 8-bit counters): 9890 [0x104b451b0, 0x104b47852), 
INFO: Loaded 1 PC tables (9890 PCs): 9890 [0x104b47858,0x104b6e278), 
INFO: Starting MinimizeCrashInputInternalStep: 58
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 58 bytes
thread '<unnamed>' panicked at alloc/src/raw_vec.rs:24:5:
capacity overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==34215== ERROR: libFuzzer: deadly signal
    #0 0x00010553bd44 in __sanitizer_print_stack_trace+0x28 (librustc-nightly_rt.asan.dylib:arm64+0x5bd44)
    #1 0x0001049d4ec0 in fuzzer::PrintStackTrace()+0x30 (fuzz_methods:arm64+0x100050ec0)
    #2 0x0001049c8174 in fuzzer::Fuzzer::CrashCallback()+0x54 (fuzz_methods:arm64+0x100044174)
    #3 0x000198146580 in _sigtramp+0x34 (libsystem_platform.dylib:arm64+0x4580)
    #4 0x8b41800198115c1c  (<unknown module>)
    #5 0x7e3a800198022a2c  (<unknown module>)
    #6 0xa67d800104a7b334  (<unknown module>)
    #7 0x000104ac51f4 in std::process::abort::h4307c511456be812+0x8 (fuzz_methods:arm64+0x1001411f4)
    #8 0x0001049c70e8 in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h1ed27d9e431f57ab+0xb8 (fuzz_methods:arm64+0x1000430e8)
    #9 0x000104a72d0c in std::panicking::rust_panic_with_hook::he9e7a691abc6490c+0x2a0 (fuzz_methods:arm64+0x1000eed0c)
    #10 0x000104a7295c in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h76e8e9b8127ee308+0x64 (fuzz_methods:arm64+0x1000ee95c)
    #11 0x000104a70728 in std::sys::backtrace::__rust_end_short_backtrace::h96d8ed392cde8e6b+0x8 (fuzz_methods:arm64+0x1000ec728)
    #12 0x000104a7263c in rust_begin_unwind+0x1c (fuzz_methods:arm64+0x1000ee63c)
    #13 0x000104ac6f20 in core::panicking::panic_fmt::hf952f5ecf9ded51a+0x1c (fuzz_methods:arm64+0x100142f20)
    #14 0x000104aa12d4 in alloc::raw_vec::capacity_overflow::h43a8f78455253237+0x34 (fuzz_methods:arm64+0x10011d2d4)
    #15 0x000104ac6adc in alloc::raw_vec::handle_error::hc9a6e8ea70a26014+0xc (fuzz_methods:arm64+0x100142adc)
    #16 0x000104ac302c in alloc::raw_vec::RawVecInner$LT$A$GT$::reserve::do_reserve_and_handle::had97d9a757eb9434 raw_vec.rs:542
    #17 0x0001049a1248 in crc_store::write::_$LT$impl$u20$crc_store..store..CrcStore$LT$I$GT$$GT$::write_with_checksums::h2c3186b58c6f72e5 write.rs:68
    #18 0x0001049a3d08 in fuzz_methods::call_method::h05994a26b8d81fb7 fuzz_methods.rs:44
    #19 0x0001049a3578 in fuzz_methods::execute_setup::h2e75c654e30afa00 fuzz_methods.rs:25
    #20 0x0001049a50e0 in fuzz_methods::_::__libfuzzer_sys_run::hfd41abab5f87629f fuzz_methods.rs:12
    #21 0x0001049a4ae8 in rust_fuzzer_test_input lib.rs:297
    #22 0x0001049bfc28 in std::panicking::try::do_call::h12046b7db380eecf+0xc4 (fuzz_methods:arm64+0x10003bc28)
    #23 0x0001049c7350 in __rust_try+0x18 (fuzz_methods:arm64+0x100043350)
    #24 0x0001049c6838 in LLVMFuzzerTestOneInput+0x16c (fuzz_methods:arm64+0x100042838)
    #25 0x0001049c9a48 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)+0x150 (fuzz_methods:arm64+0x100045a48)
    #26 0x0001049cbb54 in fuzzer::Fuzzer::MinimizeCrashLoop(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&)+0x128 (fuzz_methods:arm64+0x100047b54)
    #27 0x0001049e8dc4 in fuzzer::MinimizeCrashInputInternalStep(fuzzer::Fuzzer*, fuzzer::InputCorpus*)+0xd8 (fuzz_methods:arm64+0x100064dc4)
    #28 0x0001049ec1d8 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))+0x1c4c (fuzz_methods:arm64+0x1000681d8)
    #29 0x0001049f9970 in main+0x24 (fuzz_methods:arm64+0x100075970)
    #30 0x000197d8b150  (<unknown module>)
    #31 0x74627ffffffffffc  (<unknown module>)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 1 EraseBytes- DE: "\000\000\000\000"-; base unit: 0000000000000000000000000000000000000000
0x0,0x1,0x0,0x0,0x10,0x0,0x0,0x0,0x0,0x0,0xff,0xff,0x2,0x70,0xff,0xff,0x11,0x8,0x8,0x8,0x3b,0xf7,0xf7,0xf7,0xf7,0xf7,0xf7,0xf7,0xf6,0xf7,0xff,0xff,0xff,0xff,0xff,0xff,0x0,0xe1,0xe1,0xe1,0x9f,0x9f,0xff,0xff,0xff,0xff,0x0,0xd3,0x8c,0xe1,0xe1,0xe1,
\000\001\000\000\020\000\000\000\000\000\377\377\002p\377\377\021\010\010\010;\367\367\367\367\367\367\367\366\367\377\377\377\377\377\377\000\341\341\341\237\237\377\377\377\377\000\323\214\341\341\341
artifact_prefix='/paths/crc-store/fuzz/artifacts/fuzz_methods/'; Test unit written to /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0
Base64: AAEAABAAAAAAAP//AnD//xEICAg79/f39/f39/b3////////AOHh4Z+f/////wDTjOHh4Q==
*********************************
CRASH_MIN: minimizing crash input: '/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0' (52 bytes)
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0 2>&1
CRASH_MIN: '/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0' (52 bytes) caused a crash. Will try to minimize it further
CRASH_MIN: executing: fuzz/target/aarch64-apple-darwin/release/fuzz_methods -artifact_prefix=/paths/crc-store/fuzz/artifacts/fuzz_methods/ -runs=255 /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0 -minimize_crash_internal_step=1 -exact_artifact_path=/paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-db4dfa3a4ddccd081efe23dc9c732326d76de18c 2>&1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 544434926
INFO: Loaded 1 modules   (9890 inline 8-bit counters): 9890 [0x102dc11b0, 0x102dc3852), 
INFO: Loaded 1 PC tables (9890 PCs): 9890 [0x102dc3858,0x102dea278), 
INFO: Starting MinimizeCrashInputInternalStep: 52
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 52 bytes
INFO: Done MinimizeCrashInputInternalStep, no crashes found
CRASH_MIN: failed to minimize beyond /paths/crc-store/fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0 (52 bytes), exiting

────────────────────────────────────────────────────────────────────────────────

Minimized artifact:

	fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0

Output of `std::fmt::Debug`:

	Setup {
	    seg_len: 256,
	    buf_len: 16,
	    validate_on_read: false,
	    initial_bytes: [],
	    methods: [
	        Seek {
	            seek_from: Start(
	                17868022691004889864,
	            ),
	        },
	        Seek {
	            seek_from: Current(
	                -105965938417408,
	            ),
	        },
	        Write {
	            buf: [
	                225,
	                0,
	            ],
	        },
	    ],
	}

Reproduce with:

	cargo fuzz run fuzz_methods fuzz/artifacts/fuzz_methods/minimized-from-cbc027e406fdd4558c825e407c18a40ca083aed0
```

**Comment by xpe** [comment]
Fixed (or perhaps more fairly, avoided) with 871efe6 which limits seeks to 1 exabyte.
